screens = [
    Screen(
        wallpaper="~/Pictures/dnord4k_dark.png",
        wallpaper_mode="fill",
        top=bar.Bar(
            [
                # widget.Image(
                #   background=colors[0],
                #    filename="~/.config/qtile/icons/qtilelogo.png",
                #    margin=6,
                #    mouse_callbacks={
                #        "Button1": lambda qtile: qtile.cmd_spawn(
                #            "./.config/rofi/launchers/ribbon/launcher.sh"
                #        )
                #    },
                # ),
                widget.TextBox(
                    text="",
                    foreground=colors[13],
                    background=colors[0],
                    font="Font Awesome 5 Free Solid",
                    fontsize=28,
                    padding=20,
                    mouse_callbacks={"Button1": open_launcher},
                ),
                # widget.Sep(
                #    linewidth=2,
                #    foreground=colors[2],
                #    padding=25,
                #    size_percent=50,
                # ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.GroupBox(
                    font="Font Awesome 5 Brands",
                    visible_groups=[""],
                    **group_box_settings,
                ),
                widget.GroupBox(
                    font="Font Awesome 5 Free Solid",
                    visible_groups=["", "", "", "", ""],
                    **group_box_settings,
                ),
                widget.GroupBox(
                    font="Font Awesome 5 Brands",
                    visible_groups=[""],
                    **group_box_settings,
                ),
                widget.GroupBox(
                    font="Font Awesome 5 Free Solid",
                    visible_groups=["", "", ""],
                    **group_box_settings,
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.Sep(
                    linewidth=0,
                    foreground=colors[2],
                    background=colors[0],
                    padding=10,
                    size_percent=40,
                ),
                # widget.TextBox(
                #    text=" ",
                #    foreground=colors[7],
                #    background=colors[0],
                #    font="Font Awesome 5 Free Solid",
                # ),
                # widget.CurrentLayout(
                #    background=colors[0],
                #    foreground=colors[7],
                # ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.CurrentLayoutIcon(
                    custom_icon_paths=[os.path.expanduser("~/.config/qtile/icons")],
                    foreground=colors[2],
                    background=colors[14],
                    padding=-2,
                    scale=0.45,
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.Sep(
                    linewidth=0,
                    foreground=colors[2],
                    padding=10,
                    size_percent=50,
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.GenPollText(
                    func=taskwarrior,
                    update_interval=5,
                    foreground=colors[11],
                    background=colors[14],
                    mouse_callbacks={"Button1": finish_task},
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.Spacer(),
                widget.TextBox(
                    text=" ",
                    foreground=colors[12],
                    background=colors[0],
                    # fontsize=38,
                    font="Font Awesome 5 Free Solid",
                ),
                CustomWindowName(
                    background=colors[0],
                    foreground=colors[12],
                    width=bar.CALCULATED,
                    empty_group_string="Desktop",
                    max_chars=130,
                    mouse_callbacks={"Button2": kill_window},
                ),
                # widget.CheckUpdates(
                #    background=colors[0],
                #    foreground=colors[3],
                #    colour_have_updates=colors[3],
                #    custom_command="./.config/qtile/updates-arch-combined",
                #    display_format=" {updates}",
                #    execute=update,
                #    padding=20,
                # ),
                widget.Spacer(),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.Systray(icon_size=26, background=colors[14], padding=10),
                # CustomPomodoro(
                #    background=colors[14],
                #    fontsize=24,
                #    color_active=colors[3],
                #    color_break=colors[6],
                #    color_inactive=colors[10],
                #    timer_visible=False,
                #    prefix_active="",
                #    prefix_break="",
                #    prefix_inactive="",
                #    prefix_long_break="",
                #    prefix_paused="",
                # ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.Sep(
                    linewidth=0,
                    foreground=colors[2],
                    padding=10,
                    size_percent=50,
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.TextBox(
                    text=" ",
                    foreground=colors[8],
                    background=colors[14],
                    font="Font Awesome 5 Free Solid",
                    # fontsize=38,
                ),
                widget.PulseVolume(
                    foreground=colors[8],
                    background=colors[14],
                    limit_max_volume="True",
                    mouse_callbacks={"Button3": open_pavu},
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.Sep(
                    linewidth=0,
                    foreground=colors[2],
                    padding=10,
                    size_percent=50,
                ),
                #widget.TextBox(
                #   text="",
                #   foreground=colors[14],
                #   background=colors[0],
                #   fontsize=28,
                #   padding=0,
                #),
                #widget.TextBox(
                #    text=" ",
                #    foreground=colors[6],
                #    background=colors[14],
                #    font="Font Awesome 5 Free Brands",
                #    # fontsize=38,
                #),
                #widget.Bluetooth(
                #    background=colors[14],
                #    foreground=colors[6],
                #    hci="/dev_00_0A_45_0D_24_47",
                #    mouse_callbacks={
                #       "Button1": toggle_bluetooth,
                #       "Button3": open_bt_menu,
                #    },
                #),
                #widget.TextBox(
                #   text="",
                #   foreground=colors[14],
                #   background=colors[0],
                #   fontsize=28,
                #   padding=0,
                #),
                #widget.Sep(
                #   linewidth=0,
                #   foreground=colors[2],
                #   padding=10,
                #   size_percent=50,
                #),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.TextBox(
                    text=" ",
                    font="Font Awesome 5 Free Solid",
                    foreground=colors[7],  # fontsize=38
                    background=colors[14],
                ),
                widget.Wlan(
                    interface="wlp3s0",
                    format="{essid}",
                    foreground=colors[7],
                    background=colors[14],
                    padding=5,
                    mouse_callbacks={"Button1": open_connman},
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.Sep(
                    linewidth=0,
                    foreground=colors[2],
                    padding=10,
                    size_percent=50,
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.TextBox(
                    text=" ",
                    font="Font Awesome 5 Free Solid",
                    foreground=colors[5],  # fontsize=38
                    background=colors[14],
                ),
                widget.Clock(
                    format="%a, %b %d",
                    background=colors[14],
                    foreground=colors[5],
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.Sep(
                    linewidth=0,
                    foreground=colors[2],
                    padding=10,
                    size_percent=50,
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                widget.TextBox(
                    text=" ",
                    font="Font Awesome 5 Free Solid",
                    foreground=colors[4],  # fontsize=38
                    background=colors[14],
                ),
                widget.Clock(
                    format="%I:%M %p",
                    foreground=colors[4],
                    background=colors[14],
                    #    mouse_callbacks={"Button1": todays_date},
                ),
                widget.TextBox(
                    text="",
                    foreground=colors[14],
                    background=colors[0],
                    fontsize=28,
                    padding=0,
                ),
                # widget.Sep(
                #    linewidth=2,
                #    foreground=colors[2],
                #    padding=25,
                #    size_percent=50,
                # ),
                widget.TextBox(
                    text="⏻",
                    foreground=colors[13],
                    font="Font Awesome 5 Free Solid",
                    fontsize=34,
                    padding=20,
                    mouse_callbacks={"Button1": open_powermenu},
                ),
            ],
            48,
            margin=[0, -4, 21, -4],
        ),
        bottom=bar.Gap(18),
        left=bar.Gap(18),
        right=bar.Gap(18),
    ),
]